/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";var h=Object.defineProperty;var b=Object.getOwnPropertyDescriptor;var v=Object.getOwnPropertyNames;var F=Object.prototype.hasOwnProperty;var H=(n,t)=>{for(var e in t)h(n,e,{get:t[e],enumerable:!0})},C=(n,t,e,r)=>{if(t&&typeof t=="object"||typeof t=="function")for(let i of v(t))!F.call(n,i)&&i!==e&&h(n,i,{get:()=>t[i],enumerable:!(r=b(t,i))||r.enumerable});return n};var E=n=>C(h({},"__esModule",{value:!0}),n);var A={};H(A,{default:()=>c});module.exports=E(A);var f=require("obsidian");function x(n){var t,e;return(e=(t=n.split(/[/\\]/).pop())==null?void 0:t.replace(/\.md$/,""))!=null?e:""}var c=class extends f.Plugin{constructor(){super(...arguments);this.handleRename=(e,r)=>{var g;if(!(e instanceof f.TFile))return;let i=this.app.metadataCache.getFileCache(e),$=this.app.metadataCache.getCache(r),o=i!=null?i:$,a=(g=o==null?void 0:o.headings)==null?void 0:g.find(s=>s.level===1),u=x(r);a===void 0?this.app.vault.process(e,s=>{let l=`# ${e.basename}`;if(o!=null&&o.frontmatterPosition){let d=o.frontmatterPosition.end.offset,p=s.slice(0,d),m=s.slice(d);return`${p.trimEnd()}
${l}
${m.trimStart()}`}else return`${l}
${s.trimStart()}`}):a.heading.trim()===u&&this.app.vault.process(e,s=>{if(s.slice(a.position.start.offset+1,a.position.end.offset).trim()===u){let d=s.slice(0,a.position.start.offset),p=s.slice(a.position.end.offset),m=`# ${e.basename}`;return`${d}${m}${p}`}else return s})}}onload(){this.registerEvent(this.app.vault.on("rename",this.handleRename))}onunload(){}};
