import { describe, expect, test } from 'vitest';
import {
  generatePersonaSections,
  generateWebGuideIndex,
  parsePersona,
} from './ai.ts';

const personas = new Map([
  ['ramsay', 'Be exact.\nBe severe.'],
  ['poe', 'Be restrained.'],
]);

describe(parsePersona, () => {
  test('extracts instructions after the identifying heading', () => {
    expect(parsePersona('# poe\n\nBe restrained.\n', 'poe')).toBe(
      'Be restrained.'
    );
  });

  test('rejects a mismatched persona heading', () => {
    expect(() => parsePersona('# ramsay\n\nBe severe.\n', 'poe')).toThrow(
      'Persona poe must start with "# poe".'
    );
  });
});

describe(generatePersonaSections, () => {
  test('replaces only the contents of a persona element', () => {
    const source = [
      '# Skill',
      '',
      '## Tone',
      '',
      '<persona name="ramsay">',
      '',
      'Stale instructions.',
      '',
      '</persona>',
      '',
      'Keep this tone note.',
      '',
      '## Process',
      '',
      'Keep this process.',
      '',
    ].join('\n');

    expect(generatePersonaSections(source, personas)).toBe(
      [
        '# Skill',
        '',
        '## Tone',
        '',
        '<persona name="ramsay">',
        '',
        'Be exact.',
        'Be severe.',
        '',
        '</persona>',
        '',
        'Keep this tone note.',
        '',
        '## Process',
        '',
        'Keep this process.',
        '',
      ].join('\n')
    );
  });

  test('rejects unknown personas', () => {
    expect(() =>
      generatePersonaSections(
        '## Tone\n\n<persona name="unknown">\n\nOld.\n\n</persona>\n',
        personas,
        'skill.md'
      )
    ).toThrow('skill.md references unknown persona "unknown".');
  });

  test('rejects incomplete persona elements', () => {
    expect(() =>
      generatePersonaSections(
        '## Tone\n\n<persona name="poe">\n',
        personas,
        'skill.md'
      )
    ).toThrow(
      'skill.md must have one complete persona element per Tone section.'
    );
  });

  test('rejects persona elements outside Tone sections', () => {
    expect(() =>
      generatePersonaSections(
        '## Process\n\n<persona name="poe">\n</persona>\n',
        personas
      )
    ).toThrow('Markdown has a persona element outside a Tone section.');
  });
});

describe(generateWebGuideIndex, () => {
  test('groups and sorts guides using their titles', () => {
    expect(
      generateWebGuideIndex([
        {
          relativePath: 'ui-atoms/position-aware-tooltips.md',
          source: '# Position-Aware Tooltips\n',
        },
        {
          relativePath: 'css/css-layout.md',
          source: '# CSS Layout\n',
        },
        {
          relativePath: 'css/animate-to-intrinsic-sizes.md',
          source: '# Animate to Intrinsic Sizes\n',
        },
      ])
    ).toBe(
      [
        '<!-- Generated by src/bin/ai-sync.ts. Do not edit manually. -->',
        '',
        '# Web guide index',
        '',
        'Load only the guides relevant to the current task.',
        '',
        '## CSS',
        '',
        '- [Animate to Intrinsic Sizes](css/animate-to-intrinsic-sizes.md)',
        '- [CSS Layout](css/css-layout.md)',
        '',
        '## UI Atoms',
        '',
        '- [Position-Aware Tooltips](ui-atoms/position-aware-tooltips.md)',
        '',
      ].join('\n')
    );
  });

  test('uses a formatted filename when a guide has no title', () => {
    expect(
      generateWebGuideIndex([
        {
          relativePath: 'css/missing-title.md',
          source: 'No title.\n',
        },
      ])
    ).toContain('- [Missing Title](css/missing-title.md)');
  });

  test('rejects guides outside a category', () => {
    expect(() =>
      generateWebGuideIndex([
        {
          relativePath: 'orphan.md',
          source: '# Orphan\n',
        },
      ])
    ).toThrow('orphan.md must be inside a category.');
  });
});
