import { type ExtensionAPI } from '@earendil-works/pi-coding-agent';

// Based on https://github.com/mitsuhiko/agent-stuff/blob/main/extensions/whimsical.ts

const messages = [
  // Short
  'Vibing…',
  'Concocting…',
  'Transmuting…',
  'Pontificating…',
  'Flibbertigibbeting…',
  'Noodling…',
  'Percolating…',
  'Ruminating…',
  'Simmering…',
  'Brewing…',
  'Contemplating…',
  'Musing…',
  'Pondering…',
  'Mulling…',
  'Daydreaming…',
  'Woolgathering…',
  'Dithering…',
  'Tinkering…',
  'Fiddling…',
  'Wrangling…',
  'Jiggling…',
  'Wiggling…',
  'Meandering…',
  'Bumbling…',
  'Bamboozling…',
  'Discombobulating…',
  'Yodeling…',
  'Zigzagging…',
  'Canoodling…',
  'Schmoozing…',
  'Skedaddling…',
  'Scampering…',
  'Skittering…',
  'Swashbuckling…',
  'Oscillating…',
  'Undulating…',
  'Pulsating…',
  'Fizzing…',
  'Bubbling…',
  'Perplexing…',
  'Enchanting…',
  'Mesmerizing…',
  'Bedazzling…',
  'Sparkling…',
  'Glittering…',
  'Synthesizing…',
  'Procrastinating…',
  'Dillydallying…',
  'Lollygagging…',
  'Skulking…',
  'Lurking…',
  'Sleuthing…',
  'Rummaging…',
  'Foraging…',
  'Scavenging…',
  'Grooving…',
  'Jamming…',
  'Improvising…',
  'Freestyling…',
  'Whooshing…',
  'Swooshing…',
  'Clunking…',
  'Clanking…',
  'Rattling…',
  'Scribbling…',
  'Squiggling…',
  'Wriggling…',
  'Humming…',
  'Struggling…',

  // Long
  'Consulting the void…',
  'Asking the electrons…',
  'Bribing the compiler…',
  'Negotiating with entropy…',
  'Whispering to the bits…',
  'Tickling the stack…',
  'Massaging the heap…',
  'Appeasing the garbage collector…',
  'Summoning semicolons…',
  'Herding pointers…',
  'Untangling spaghetti…',
  'Polishing the algorithms…',
  'Consulting ancient scrolls…',
  'Reading tea leaves…',
  'Shaking the magic 8-ball…',
  'Warming up the hamsters…',
  'Spinning up the squirrels…',
  'Caffeinating…',
  'Existentially questioning…',
  'Having a little think…',
  'Stroking chin thoughtfully…',
  'Squinting at the problem…',
  'Staring into the abyss…',
  'Abyss staring back…',
  'Achieving enlightenment…',
  'Transcending mere computation…',
  'Ascending to a higher plane…',
  'Communing with the machine spirit…',
  'Performing arcane rituals…',
  'Consulting the oracle…',
  'Divining the answer…',
  'Scrying the codebase…',
  'Dowsing for bugs…',
  'Shuffling bits around…',
  'Aligning the chakras…',
  'Reversing the polarity…',
  'Calibrating the flux capacitor…',
  'Adjusting the cosmic frequency…',
  'Waiting for a sign…',
  'Hoping for the best…',
  'Willing it into existence…',
  'Believing really hard…',
  'Bargaining with fate…',
  'Greasing the gears…',
  'Oiling the cogs…',
  'Winding up the clockwork…',
  'Stoking the furnace…',
  'Watering the logic tree…',
  'Pruning the decision branches…',
  'Teaching old code new tricks…',
  'Having a moment of clarity…',
  'Experiencing a flash of insight…',
  'Asking the hamsters to run faster…',
  'Convincing the pixels to cooperate…',
  'Bribing the byte fairies…',
  'Whispering passwords to the void…',
  'Seducing the semicolons…',
  'Hypnotizing the hash tables…',
  'Mesmerizing the memory banks…',
  'Enchanting the error handlers…',
  'Bewitching the boolean logic…',
  'Spellbinding the stack frames…',
  'Hexing the hexadecimals…',
  'Releasing the references…',
  'Unbinding the variables…',
  'Snorkeling through the streams…',
  'Maturing the methods…',
  'Adding a dash of elegance…',
  'Sprinkling some magic dust…',
  'Folding in the features…',

  // Extra
  'Klatzing…',
  'Tram-param-param-pam-pam…',
  'Trum-purum-purum-pum-pum…',
  'Counting sheep…',
  'Yelling at a cloud…',
  'Playing with fonts…',
  'Playing with fire…',
  'Pushing pixels…',
  'Sacrificing a lamb…',
  'Praying to His Noodliness…',
  'Having a little snack…',
  'Calming exceptions…',
  'Excusing exceptions…',
  'Reading forbidden books…',
  'Fishing floating points…',
  'Purifying functions…',
  'Unwinding for loops…',
  'Sticking nose into someone’s code…',
  'Typing furiously…',
  'Lubricating with fresh butter…',
  'Squeezing the cat…',
  'Chasing tail…',
  'Barking at a wrong tree…',
  'Drawing in sand…',
  'Boiling spaghetti…',
  'Whistling a tune…',
  'Scratching head…',
  'Having a short nap…',
  'Grilling kebab-case-variables…',
  'Charming snake_case_variables…',
  'Passing camelCaseVariables through needle’s eye…',
  'SCREAMING_AT_SNAKE_CASE_VARIABLES…',
  'Converting tabs to spaces…',
  'Converting spaces to tabs…',
  'Plotting…',
  'Scheming…',
  'Wondering whether god exists…',
  'Questioning motives…',
  'Thinking of lunch…',
  'Grokking algorithms…',
  'Expecto patronum…',
  'Avada kedavra…',
  'Killing two birds with one stone…',
  'Intensifying…',
  'Rolling like cheese in butter…',
  'Raccooning…',
  'Squirreling…',
  'Running like a headless chicken…',
  'Loosing threads…',
  'Panicking…',
  'Pushing tempo…',
  'Buying tokens on black market…',
  'Starting fire…',
  'Summoning a demon…',
  'Talking to ghosts of mainframe developers…',
  'Looking into crystal ball…',
  'Tuning a radio…',
  'Receiving a transmission from USSR…',
  'Persevering…',
  'Surviving…',
  'Getting getters…',
  'Setting setters…',
  'Surfing error squiggles…',
  'Aligning pointers…',
  'Returning callbacks’ calls…',
  'Thinking v. hard…',
  'Hissing silently…',
  'Herding cats…',
  'Demystifying…',
  'Typing type declarations…',
  'Clack, clack, clack…',
  'Closing closures…',
  'Adding semicolons…',
  'Yoloing…',
  'Rubberducking…',
  'Tracing stack trace…',
  'Falling into rabbit hole…',
  'Creeping scope…',
  'Dotting loop indices…',
  'Shivering…',
  'Accepting criteria…',
  'Transgressing…',
  'Signing code with blood…',
  'Burrowing…',
];

function pickRandom(): string {
  return messages[Math.floor(Math.random() * messages.length)];
}

export default function Whimsical(pi: ExtensionAPI) {
  pi.on('turn_start', (_event, ctx) => {
    ctx.ui.setWorkingMessage(pickRandom());
  });

  pi.on('turn_end', (_event, ctx) => {
    // Reset for next time
    ctx.ui.setWorkingMessage();
  });
}
