; Squirrelsong for zsh-fast-syntax-highlighting
; https://sapegin.me/squirrelsong/

[base]
default = none
unknown-token = red,bold
commandseparator = cyan,bold
redirection = cyan,bold
here-string-tri = yellow
here-string-text = 18
here-string-var = cyan,bg:18
exec-descriptor = yellow,bold
comment = black,bold
correct-subtle = 12
incorrect-subtle = red
subtle-separator = green
subtle-bg = bg:18
secondary = free
recursive-base =

[command-point]
reserved-word = magenta,bold
subcommand = yellow
alias = blue,bold
suffix-alias = blue,bold
global-alias = blue,bold
builtin = blue,bold
function = blue,bold
command = blue,bold
precommand = green
hashed-command = green
single-sq-bracket = green
double-sq-bracket = green
double-paren = yellow

[paths]
path = magenta
pathseparator =
path-to-dir = magenta,underline
globbing = magenta,bold
globbing-ext = 13

[brackets]
paired-bracket = bg:blue
bracket-level-1 = green,bold
bracket-level-2 = yellow,bold
bracket-level-3 = cyan,bold

[arguments]
single-hyphen-option = cyan
double-hyphen-option = cyan
back-quoted-argument = green
single-quoted-argument = green
double-quoted-argument = green
dollar-quoted-argument = green
optarg-string = green
optarg-number = yellow

[in-string]
; backslash in $'...'
back-dollar-quoted-argument = green,bold
; backslash or $... in "..."
back-or-dollar-double-quoted-argument = blue

[other]
variable = 113
assign = none
assign-array-bracket = green
history-expansion = blue,bold

[math]
mathvar = blue,bold
mathnum = magenta
matherr = red

[for-loop]
forvar = none
fornum = magenta
; operator
foroper = yellow
; separator
forsep = yellow,bold

[case]
case-input = green
case-parentheses = yellow
case-condition = bg:blue
