import { type ExtensionAPI } from '@earendil-works/pi-coding-agent';

// Based on https://github.com/mitsuhiko/agent-stuff/blob/main/extensions/whimsical.ts

const messages = [
  // Short
  'Vibing…',
  'Concocting…',
  'Transmuting…',
  'Pontificating…',
  'Flibbertigibbeting…',
  'Noodling…',
  'Percolating…',
  'Ruminating…',
  'Simmering…',
  'Brewing…',
  'Contemplating…',
  'Musing…',
  'Pondering…',
  'Mulling…',
  'Daydreaming…',
  'Woolgathering…',
  'Dithering…',
  'Tinkering…',
  'Fiddling…',
  'Wrangling…',
  'Jiggling…',
  'Wiggling…',
  'Meandering…',
  'Bumbling…',
  'Bamboozling…',
  'Discombobulating…',
  'Yodeling…',
  'Zigzagging…',
  'Canoodling…',
  'Schmoozing…',
  'Skedaddling…',
  'Scampering…',
  'Skittering…',
  'Swashbuckling…',
  'Oscillating…',
  'Undulating…',
  'Pulsating…',
  'Fizzing…',
  'Bubbling…',
  'Perplexing…',
  'Mystifying…',
  'Enchanting…',
  'Bewitching…',
  'Mesmerizing…',
  'Bedazzling…',
  'Sparkling…',
  'Glittering…',
  'Sublimating…',
  'Synthesizing…',
  'Procrastinating…',
  'Dillydallying…',
  'Lollygagging…',
  'Dawdling…',
  'Malingering…',
  'Skulking…',
  'Lurking…',
  'Sleuthing…',
  'Rummaging…',
  'Foraging…',
  'Scavenging…',
  'Grooving…',
  'Jamming…',
  'Improvising…',
  'Freestyling…',
  'Whooshing…',
  'Swooshing…',
  'Clunking…',
  'Clanking…',
  'Rattling…',
  'Scribbling…',
  'Squiggling…',
  'Wriggling…',
  'Humming…',
  'Struggling…',

  // Long
  'Consulting the void…',
  'Asking the electrons…',
  'Bribing the compiler…',
  'Negotiating with entropy…',
  'Whispering to the bits…',
  'Tickling the stack…',
  'Massaging the heap…',
  'Appeasing the garbage collector…',
  'Summoning semicolons…',
  'Herding pointers…',
  'Untangling spaghetti…',
  'Polishing the algorithms…',
  'Consulting ancient scrolls…',
  'Reading tea leaves…',
  'Shaking the magic 8-ball…',
  'Warming up the hamsters…',
  'Spinning up the squirrels…',
  'Caffeinating…',
  'Existentially questioning…',
  'Having a little think…',
  'Stroking chin thoughtfully…',
  'Squinting at the problem…',
  'Staring into the abyss…',
  'Abyss staring back…',
  'Achieving enlightenment…',
  'Transcending mere computation…',
  'Ascending to a higher plane…',
  'Communing with the machine spirit…',
  'Performing arcane rituals…',
  'Invoking elder functions…',
  'Consulting the oracle…',
  'Divining the answer…',
  'Scrying the codebase…',
  'Dowsing for bugs…',
  'Shuffling bits around…',
  'Aligning the chakras…',
  'Reversing the polarity…',
  'Calibrating the flux capacitor…',
  'Charging the crystals…',
  'Tuning the vibrations…',
  'Adjusting the cosmic frequency…',
  'Waiting for a sign…',
  'Hoping for the best…',
  'Manifesting solutions…',
  'Willing it into existence…',
  'Believing really hard…',
  'Politely asking the CPU…',
  'Bribing the runtime…',
  'Flirting with the database…',
  'Sweet-talking the API…',
  'Negotiating with deadlines…',
  'Having words with the cache…',
  'Reasoning with the memory…',
  'Pleading with the logs…',
  'Bargaining with fate…',
  'Consulting the rubber duck…',
  'Interrogating the stack trace…',
  'Cross-examining the debugger…',
  'Petitioning the kernel…',
  'Lobbying the scheduler…',
  'Schmoozing the network…',
  'Buttering up the firewall…',
  'Checking under the hood…',
  'Shaking loose the cobwebs…',
  'Dusting off the neurons…',
  'Greasing the gears…',
  'Oiling the cogs…',
  'Winding up the clockwork…',
  'Stoking the furnace…',
  'Feeding the machine…',
  'Watering the logic tree…',
  'Pruning the decision branches…',
  'Harvesting the outputs…',
  'Planting computational seeds…',
  'Nurturing the algorithm…',
  'Taming wild pointers…',
  'Herding cats in memory…',
  'Teaching old code new tricks…',
  'Whispering sweet nothings to the compiler…',
  'Serenading the syntax…',
  'Dancing with dependencies…',
  'Waltzing through the codebase…',
  'Tangoing with type errors…',
  'Having a moment of clarity…',
  'Experiencing a flash of insight…',
  'Channeling the ancient developers…',
  'Receiving transmissions from the cloud…',
  'Asking the hamsters to run faster…',
  'Convincing the pixels to cooperate…',
  'Bribing the byte fairies…',
  'Whispering passwords to the void…',
  'Negotiating with cosmic rays…',
  'Seducing the semicolons…',
  'Wooing the while loops…',
  'Charming the curly braces…',
  'Hypnotizing the hash tables…',
  'Mesmerizing the memory banks…',
  'Enchanting the error handlers…',
  'Bewitching the boolean logic…',
  'Spellbinding the stack frames…',
  'Hexing the hexadecimals…',
  'Jinxing the JSON parsers…',
  'Cursing the cache misses…',
  'Blessing the build process…',
  'Anointing the algorithms…',
  'Consecrating the callbacks…',
  'Sanctifying the source code…',
  'Exorcising the exceptions…',
  'Cleansing the closures…',
  'Baptizing the binary…',
  'Absolving the abstractions…',
  'Redeeming the recursion…',
  'Pardoning the pointers…',
  'Liberating the lambdas…',
  'Emancipating the enums…',
  'Releasing the references…',
  'Unbinding the variables…',
  'Untying the type knots…',
  'Decoding the mysteries…',
  'Cracking the conundrums…',
  'Solving the riddles of RAM…',
  'Unlocking the secrets of silicon…',
  'Discovering hidden semicolons…',
  'Excavating ancient APIs…',
  'Spelunking through the stack…',
  'Snorkeling through the streams…',
  'Surfing the syntax waves…',
  'Maturing the methods…',
  'Seasoning the solutions…',
  'Garnishing the getters…',
  'Adding a dash of elegance…',
  'Sprinkling some magic dust…',
  'Drizzling debug sauce…',
  'Folding in the features…',

  // Extra
  'Klatzing…',
  'Tram-param-param-pam-pam…',
  'Trum-purum-purum-pum-pum…',
  'Counting sheep…',
  'Yelling at a cloud…',
  'Playing with fonts…',
  'Playing with fire…',
  'Pushing pixels…',
  'Sacrificing a lamb…',
  'Praying to His Noodliness…',
  'Having a little snack…',
  'Calming the exceptions…',
  'Reading forbidden books…',
  'Fishing the floating points…',
  'Purifying the functions…',
  'Unwinding the for loops…',
  'Sticking nose into someone’s code…',
  'Typing furiously…',
  'Lubricating the mechanism with fresh butter…',
  'Squeezing the cat…',
  'Chasing tail…',
  'Barking at the wrong tree…',
  'Drawing in sand…',
  'Boiling spaghetti…',
  'Whistling a tune…',
  'Scratching head…',
  'Having a short nap…',
  'Grilling kebab-case-variables…',
  'Charming snake_case_variables…',
  'Passing camelCaseVariables through needle’s eye…',
  'SCREAMING_AT_SNAKE_CASE_VARIABLES…',
  'Converting tabs to spaces…',
  'Converting spaces to tabs…',
  'Plotting…',
  'Scheming…',
  'Wondering whether god exists…',
  'Questioning motives…',
  'Thinking of lunch…',
  'Grokking algorithms…',
  'Expecto patronum…',
  'Avada kedavra…',
  'Killing two birds with one stone…',
];

function pickRandom(): string {
  return messages[Math.floor(Math.random() * messages.length)];
}

export default function Whimsical(pi: ExtensionAPI) {
  pi.on('turn_start', (_event, ctx) => {
    ctx.ui.setWorkingMessage(pickRandom());
  });

  pi.on('turn_end', (_event, ctx) => {
    // Reset for next time
    ctx.ui.setWorkingMessage();
  });
}
