/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";var d=Object.defineProperty;var i=Object.getOwnPropertyDescriptor;var m=Object.getOwnPropertyNames;var c=Object.prototype.hasOwnProperty;var n=(o,e)=>{for(var t in e)d(o,t,{get:e[t],enumerable:!0})},p=(o,e,t,g)=>{if(e&&typeof e=="object"||typeof e=="function")for(let l of m(e))!c.call(o,l)&&l!==t&&d(o,l,{get:()=>e[l],enumerable:!(g=i(e,l))||g.enumerable});return o};var u=o=>p(d({},"__esModule",{value:!0}),o);var r={};n(r,{default:()=>a});module.exports=u(r);var s=require("obsidian"),a=class extends s.Plugin{constructor(){super(...arguments);this.toggle=()=>{document.body.classList.toggle("zen-mode-supreme-active")}}onload(){this.addCommand({id:"zen-mode-supreme-toggle",name:"Toggle",callback:this.toggle})}onunload(){}};
