/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";var h=Object.defineProperty;var g=Object.getOwnPropertyDescriptor;var E=Object.getOwnPropertyNames;var R=Object.prototype.hasOwnProperty;var v=(n,t)=>{for(var e in t)h(n,e,{get:t[e],enumerable:!0})},F=(n,t,e,i)=>{if(t&&typeof t=="object"||typeof t=="function")for(let r of E(t))!R.call(n,r)&&r!==e&&h(n,r,{get:()=>t[r],enumerable:!(i=g(t,r))||i.enumerable});return n};var T=n=>F(h({},"__esModule",{value:!0}),n);var S={};v(S,{default:()=>o});module.exports=T(S);var l=require("obsidian"),x=/^---\r?\n[\s\S]*?\r?\n---/,A=/^# (.+)$/m;function M(n){var t,e;return(e=(t=n.split(/[/\\]/).pop())==null?void 0:t.replace(/\.md$/,""))!=null?e:""}var o=class extends l.Plugin{constructor(){super(...arguments);this.handleRename=(e,i)=>{if(!(e instanceof l.TFile))return;let r=M(i);this.app.vault.process(e,a=>{var f;let c=`# ${e.basename}`,m=a.match(x),d=m?m[0].length:0,u=a.slice(d),s=u.match(A);if(s===null)return m?`${a.slice(0,d).trimEnd()}

${c}

${u.trimStart()}`:`${c}

${a.trimStart()}`;if(s[1].trim()===r){let p=d+((f=s.index)!=null?f:0),$=a.slice(0,p),b=a.slice(p+s[0].length);return`${$}${c}${b}`}return a})}}onload(){this.registerEvent(this.app.vault.on("rename",this.handleRename))}onunload(){}};
