// Disable "Sync and save data"
user_pref('identity.fxaccounts.enabled', false);
// Disable annoying tooltips for
user_pref('browser.tabs.hoverPreview.enabled', false);
// Don't show warning on about:config
user_pref('browser.aboutConfig.showWarning', false);
// Disable Pocket extension
user_pref('extensions.pocket.enabled', false);
// Disable AI chatbot
user_pref('browser.ml.chat.enabled', false);
// Disable some Telemetry
user_pref('browser.crashReports.unsubmittedCheck.autoSubmit', false);
user_pref('browser.crashReports.unsubmittedCheck.autoSubmit2', false);
user_pref('browser.crashReports.unsubmittedCheck.enabled', false);
user_pref('datareporting.healthreport.service.enabled', false);
user_pref('datareporting.healthreport.uploadEnabled', false);
user_pref('datareporting.policy.dataSubmissionEnabled', false);

// user_pref("app.normandy.api_url", "");
// user_pref("app.normandy.enabled", false);
// user_pref("app.shield.optoutstudies.enabled", false);
// user_pref("beacon.enabled", false);
// user_pref("breakpad.reportURL", "");
// user_pref("browser.disableResetPrompt", true);
// user_pref("browser.newtabpage.activity-stream.section.highlights.includePocket", false);
// user_pref("browser.newtabpage.enabled", false);
// user_pref("browser.newtabpage.enhanced", false);
// user_pref("browser.newtabpage.introShown", true);
// user_pref("browser.safebrowsing.appRepURL", "");
// user_pref("browser.safebrowsing.blockedURIs.enabled", false);
// user_pref("browser.safebrowsing.downloads.enabled", false);
// user_pref("browser.safebrowsing.downloads.remote.enabled", false);
// user_pref("browser.safebrowsing.downloads.remote.url", "");
// user_pref("browser.safebrowsing.enabled", false);
// user_pref("browser.safebrowsing.malware.enabled", false);
// user_pref("browser.safebrowsing.phishing.enabled", false);
// user_pref("browser.selfsupport.url", "");
// user_pref("browser.send_pings", false);
// user_pref("browser.sessionstore.privacy_level", 0);
// user_pref("browser.shell.checkDefaultBrowser", false);
// user_pref("browser.startup.homepage_override.mstone", "ignore");
// user_pref("browser.tabs.crashReporting.sendReport", false);
// user_pref("browser.urlbar.groupLabels.enabled", false);
// user_pref("browser.urlbar.quicksuggest.enabled", false);
// user_pref("browser.urlbar.trimURLs", false);
// user_pref("device.sensors.ambientLight.enabled", false);
// user_pref("device.sensors.enabled", false);
// user_pref("device.sensors.motion.enabled", false);
// user_pref("device.sensors.orientation.enabled", false);
// user_pref("device.sensors.proximity.enabled", false);
// user_pref("dom.battery.enabled", false);
// user_pref("dom.private-attribution.submission.enabled", false);
// user_pref("experiments.activeExperiment", false);
// user_pref("experiments.enabled", false);
// user_pref("experiments.manifest.uri", "");
// user_pref("experiments.supported", false);
// user_pref("extensions.autoDisableScopes", 14);
// user_pref("extensions.blocklist.enabled", false);
// user_pref("extensions.getAddons.cache.enabled", false);
// user_pref("extensions.getAddons.showPane", false);
// user_pref("extensions.greasemonkey.stats.optedin", false);
// user_pref("extensions.greasemonkey.stats.url", "");
// user_pref("extensions.shield-recipe-client.api_url", "");
// user_pref("extensions.shield-recipe-client.enabled", false);
// user_pref("extensions.webservice.discoverURL", "");
// user_pref("media.autoplay.default", 0);
// user_pref("media.autoplay.enabled", true);
// user_pref("media.video_stats.enabled", false);
// user_pref("network.allow-experiments", false);
// user_pref("network.captive-portal-service.enabled", false);
// user_pref("network.cookie.cookieBehavior", 1);
// user_pref("network.http.referer.spoofSource", true);
// user_pref("privacy.donottrackheader.enabled", true);
// user_pref("privacy.donottrackheader.value", 1);
// user_pref("privacy.query_stripping", true);
// user_pref("privacy.trackingprotection.cryptomining.enabled", true);
// user_pref("privacy.trackingprotection.enabled", true);
// user_pref("privacy.trackingprotection.fingerprinting.enabled", true);
// user_pref("privacy.trackingprotection.pbmode.enabled", true);
// user_pref("privacy.usercontext.about_newtab_segregation.enabled", true);
// user_pref("security.ssl.disable_session_identifiers", true);
// user_pref("services.sync.prefs.sync.browser.newtabpage.activity-stream.showSponsoredTopSite", false);
// user_pref("signon.autofillForms", false);
// user_pref("toolkit.telemetry.archive.enabled", false);
// user_pref("toolkit.telemetry.bhrPing.enabled", false);
// user_pref("toolkit.telemetry.cachedClientID", "");
// user_pref("toolkit.telemetry.enabled", false);
// user_pref("toolkit.telemetry.firstShutdownPing.enabled", false);
// user_pref("toolkit.telemetry.hybridContent.enabled", false);
// user_pref("toolkit.telemetry.newProfilePing.enabled", false);
// user_pref("toolkit.telemetry.prompted", 2);
// user_pref("toolkit.telemetry.rejected", true);
// user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
// user_pref("toolkit.telemetry.server", "");
// user_pref("toolkit.telemetry.shutdownPingSender.enabled", false);
// user_pref("toolkit.telemetry.unified", false);
// user_pref("toolkit.telemetry.unifiedIsOptIn", false);
// user_pref("toolkit.telemetry.updatePing.enabled", false);
// user_pref("webgl.renderer-string-override", " ");
// user_pref("webgl.vendor-string-override", " ");
