/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var n=Object.defineProperty;var s=Object.getOwnPropertyDescriptor;var c=Object.getOwnPropertyNames;var l=Object.prototype.hasOwnProperty;var m=(o,e)=>{for(var r in e)n(o,r,{get:e[r],enumerable:!0})},p=(o,e,r,i)=>{if(e&&typeof e=="object"||typeof e=="function")for(let t of c(e))!l.call(o,t)&&t!==r&&n(o,t,{get:()=>e[t],enumerable:!(i=s(e,t))||i.enumerable});return o};var f=o=>p(n({},"__esModule",{value:!0}),o);var g={};m(g,{default:()=>d});module.exports=f(g);var a=require("obsidian"),d=class extends a.Plugin{foldProperties(){let e=document.querySelector(".workspace-leaf.mod-active");e&&(e.querySelector(".metadata-container.is-collapsed")||(console.warn("folding properties"),this.app.commands.executeCommandById("editor:toggle-fold-properties")))}async onload(){this.registerEvent(this.app.workspace.on("file-open",this.foldProperties.bind(this)))}};

/* nosourcemap */